name: Daily Quota Tracker

on:
  schedule:
    - cron: "0 21 * * *" # 00:00 +3 timezone -> 21:00 UTC
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run quota tracker
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LND_NUMBER: ${{ secrets.LND_NUMBER }}
          LND_PASS: ${{ secrets.LND_PASS }}
          START_GB: ${{ secrets.START_GB }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python src/main.py
